// AUTO-GENERATED by gen_mainline_initializer_stubs.sh.
// Edit only if a real OH-side service replaces the no-op.
package android.bluetooth;

/** Mainline APEX stub.  The real impl lives in an APEX module
 * that OH does not ship; stubs the call sites in
 * SystemServiceRegistry.<clinit> +
 * ActivityThread.initializeMainlineModules so they link cleanly. */
public final class BluetoothFrameworkInitializer {
    private BluetoothFrameworkInitializer() {}
    public static void registerServiceWrappers() { /* no-op */ }
    public static void setBluetoothServiceManager(android.os.BluetoothServiceManager a0) { /* no-op */ }
    public static void setBinderCallsStatsInitializer(java.util.function.Consumer<android.content.Context> a0) { /* no-op */ }
}
