/* complete bridge compat stub */
void* _ZTIN4OHOS10AppExecFwk16AppSchedulerHostE[8]={0};
void* _ZTIN4OHOS13IPCObjectStubE[8]={0};
void* _ZTIN4OHOS13IRemoteObjectE[8]={0};
void* _ZTIN4OHOS3MMI19IInputEventConsumerE[8]={0};
void* _ZTIN4OHOS5AAFwk20AbilitySchedulerStubE[8]={0};
void* _ZTIN4OHOS5AAFwk21AbilityConnectionStubE[8]={0};
void* _ZTIN4OHOS5Rosen16SessionStageStubE[8]={0};
void* _ZTIN4OHOS5Rosen22WindowManagerAgentStubE[8]={0};
void* _ZTIN4OHOS7RefBaseE[8]={0};
void* _ZTIN4OHOS8EventFwk21CommonEventSubscriberE[8]={0};
void _Z17sk_abort_no_printv(void){}
void _Z8SkDebugfPKcz(void){}
void _ZN10oh_adapter21WindowCallbackAdapterC1EP7_JavaVMP8_jobject(void){}
void _ZN11SkColorInfoD1Ev(void){}
void _ZN11SkImageInfo4MakeEii11SkColorType11SkAlphaType5sk_spI12SkColorSpaceE(void){}
void _ZN12SkBmpDecoder5IsBmpEPKvm(void){}
void _ZN12SkBmpDecoder6DecodeENSt3__h10unique_ptrI8SkStreamNS0_14default_deleteIS2_EEEEPN7SkCodec6ResultEPv(void){}
void _ZN12SkColorSpace4MakeERK16skcms_ICCProfile(void){}
void _ZN12SkColorSpace8MakeSRGBEv(void){}
void _ZN12SkGifDecoder5IsGifEPKvm(void){}
void _ZN12SkGifDecoder6DecodeENSt3__h10unique_ptrI8SkStreamNS0_14default_deleteIS2_EEEEPN7SkCodec6ResultEPv(void){}
void _ZN12SkIcoDecoder5IsIcoEPKvm(void){}
void _ZN12SkIcoDecoder6DecodeENSt3__h10unique_ptrI8SkStreamNS0_14default_deleteIS2_EEEEPN7SkCodec6ResultEPv(void){}
void _ZN12SkPngDecoder5IsPngEPKvm(void){}
void _ZN12SkPngDecoder6DecodeENSt3__h10unique_ptrI8SkStreamNS0_14default_deleteIS2_EEEEPN7SkCodec6ResultEPv(void){}
void _ZN13SkJpegDecoder6DecodeENSt3__h10unique_ptrI8SkStreamNS0_14default_deleteIS2_EEEEPN7SkCodec6ResultEPv(void){}
void _ZN13SkJpegDecoder6IsJpegEPKvm(void){}
void _ZN13SkWbmpDecoder6DecodeENSt3__h10unique_ptrI8SkStreamNS0_14default_deleteIS2_EEEEPN7SkCodec6ResultEPv(void){}
void _ZN13SkWbmpDecoder6IsWbmpEPKvm(void){}
void _ZN13SkWebpDecoder6DecodeENSt3__h10unique_ptrI8SkStreamNS0_14default_deleteIS2_EEEEPN7SkCodec6ResultEPv(void){}
void _ZN13SkWebpDecoder6IsWebpEPKvm(void){}
void _ZN14SkMemoryStreamC1E5sk_spI6SkDataE(void){}
void _ZN14SkMemoryStreamC1EPKvmb(void){}
void _ZN4OHOS10AppExecFwk11EventRunner6CreateERKNSt3__h12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE(void){}
void _ZN6SkData16MakeFromFileNameEPKc(void){}
void _ZN6SkDataD1Ev(void){}
void _ZN6SkDatadlEPv(void){}
void _ZN7SkCodec14MakeFromStreamENSt3__h10unique_ptrI8SkStreamNS0_14default_deleteIS2_EEEEPNS_6ResultEP16SkPngChunkReaderNS_15SelectionPolicyE(void){}
void _ZN7SkCodec9getPixelsERK11SkImageInfoPvmPKNS_7OptionsE(void){}
void _ZN7android10RpcSession30getFileDescriptorTransportModeEv(void){}
void _ZN7android10zeroMemoryEPhm(void){}
void _ZN7android13ResStringPoolC1EPKvmb(void){}
void _ZN7android17dupFileDescriptorEiPi(void){}
void _ZN7android33register_android_view_MotionEventEP7_JNIEnv(void){}
void _ZN7android37register_android_content_AssetManagerEP7_JNIEnv(void){}
void _ZN7android4skia19FrontBufferedStream4MakeENSt3__h10unique_ptrI8SkStreamNS2_14default_deleteIS4_EEEEm(void){}
void _ZN7android6binder6Status14readFromParcelERKNS_6ParcelE(void){}
void _ZN7android6binder6Status17fromExceptionCodeEiRKNS_7String8E(void){}
void _ZN7android6binder6Status2okEv(void){}
void _ZN7android7BBinder11setParceledEv(void){}
void _ZN7android7HexDumpC1EPKvmm(void){}
void _ZN7android8RpcState15onBinderLeavingERKNS_2spINS_10RpcSessionEEERKNS1_INS_7IBinderEEEPm(void){}
void _ZN7android8RpcState16onBinderEnteringERKNS_2spINS_10RpcSessionEEEmPNS1_INS_7IBinderEEE(void){}
void _ZN7android8RpcState21flushExcessBinderRefsERKNS_2spINS_10RpcSessionEEEmRKNS1_INS_7IBinderEEE(void){}
void _ZN7android8internal9Stability22tryMarkCompilationUnitEPNS_7IBinderE(void){}
void _ZN7android8internal9Stability7getReprEPNS_7IBinderE(void){}
void _ZN7android8internal9Stability7setReprEPNS_7IBinderEij(void){}
void _ZN7androidlsERNSt3__h13basic_ostreamIcNS0_11char_traitsIcEEEERKNS_7HexDumpE(void){}
void _ZN8SkCodecs8RegisterENS_7DecoderE(void){}
void _ZNK11SkColorInfo13bytesPerPixelEv(void){}
void _ZNK4OHOS10AppExecFwk13Configuration7GetItemERKNSt3__h12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE(void){}
void _ZNK4OHOS10AppExecFwk13Configuration7GetNameEv(void){}
void _ZNK7android6binder6Status13writeToParcelEPNS_6ParcelE(void){}
void _ZNK7android8BpBinder10rpcSessionEv(void){}
void _ZNK7android8BpBinder11isRpcBinderEv(void){}
void ashmem_create_region(void){}
void ashmem_get_size_region(void){}
void ashmem_set_prot_region(void){}
void ashmem_valid(void){}
void sk_num(void){}
void sk_value(void){}
